/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package condominio.view.Interface;

import javax.swing.JOptionPane;

/**
 *
 * @author Rafa1
 */
public class EditarMorador extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaMorador
     */
    public EditarMorador() {
        initComponents();
    }
     private void cleanFields(){
    txtnome.setText("");
    txttel.setText("");
    txtapto.setText("");
    txtcpf.setText("");
    txtsenha.setText("");
    txttipo.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        ConsultarUsuario = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcpf = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txttipo = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        txtapto = new javax.swing.JTextField();
        txtsenha = new javax.swing.JTextField();
        JLBCPF = new javax.swing.JLabel();
        btnapagar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Usuario");
        setToolTipText("");

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Senha");

        jLabel2.setText("Nome");

        jLabel3.setText("Telefone");

        jLabel6.setText("Tipo");

        jLabel5.setText("Apartamento");

        txttipo.setEditable(false);

        JLBCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLBCPF.setText("CPF");

        btnapagar.setBackground(new java.awt.Color(255, 0, 0));
        btnapagar.setText("Apagar Registro");
        btnapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapagarActionPerformed(evt);
            }
        });

        btneditar.setBackground(new java.awt.Color(255, 255, 0));
        btneditar.setText("Editar Registro");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        ConsultarUsuario.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ConsultarUsuario.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ConsultarUsuario.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ConsultarUsuario.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ConsultarUsuario.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ConsultarUsuario.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ConsultarUsuario.setLayer(txtcpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ConsultarUsuario.setLayer(txtnome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ConsultarUsuario.setLayer(txttipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ConsultarUsuario.setLayer(txttel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ConsultarUsuario.setLayer(txtapto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ConsultarUsuario.setLayer(txtsenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ConsultarUsuario.setLayer(JLBCPF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ConsultarUsuario.setLayer(btnapagar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ConsultarUsuario.setLayer(btneditar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ConsultarUsuarioLayout = new javax.swing.GroupLayout(ConsultarUsuario);
        ConsultarUsuario.setLayout(ConsultarUsuarioLayout);
        ConsultarUsuarioLayout.setHorizontalGroup(
            ConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultarUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConsultarUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConsultarUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtapto, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConsultarUsuarioLayout.createSequentialGroup()
                        .addGroup(ConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ConsultarUsuarioLayout.createSequentialGroup()
                                .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(ConsultarUsuarioLayout.createSequentialGroup()
                                .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(ConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnapagar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(32, Short.MAX_VALUE))))
                    .addGroup(ConsultarUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        ConsultarUsuarioLayout.setVerticalGroup(
            ConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarUsuarioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(ConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBCPF)
                    .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(ConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtapto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(btnapagar)
                .addGap(18, 18, 18)
                .addComponent(btneditar)
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConsultarUsuario)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConsultarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cpf = txtcpf.getText() ;

        Pessoa pessoa = PessoaDAO.buscarPorCPF(cpf);
        Pessoa people = new Pessoa();

        if(people.tipo == true){
            txttipo.setText("Administrador");
        } else {
            txttipo.setText("Morador");

        }

        if(cpf != null){
            txtnome.setText(pessoa.nome);
            txttel.setText(pessoa.telefone);
            txtapto.setText(pessoa.apartamento);
            txtsenha.setText(pessoa.senha);

        }else if (people.cpf == null){
            JOptionPane.showMessageDialog(this, "Nada encontrado.");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapagarActionPerformed
    Pessoa pessoa = new Pessoa();
    String cpf = txtcpf.getText();
    int result = PessoaDAO.apagarPorCpf(cpf);
    if (result > 0) {
             JOptionPane.showMessageDialog(this,result + " registro(s) apagado(s)");
        } else {
           JOptionPane.showMessageDialog(this, "Nada atualizado.");
        }           }//GEN-LAST:event_btnapagarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        String Stringcpf = txtcpf.getText();
       
        
        int result = PessoaDAO.atualizarMorador(txtcpf.getText(), txtnome.getText(), txtsenha.getText(), txtapto.getText(), txttel.getText());
        
        
        
        if(result > 0) {
           JOptionPane.showMessageDialog(this,result + " registro(s) atualizado(s)");
        } else {
             JOptionPane.showMessageDialog(this, "Nada atualizado.");
        }
    }//GEN-LAST:event_btneditarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane ConsultarUsuario;
    private javax.swing.JLabel JLBCPF;
    private javax.swing.JButton btnapagar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtapto;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtsenha;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField txttipo;
    // End of variables declaration//GEN-END:variables
}
